name = "amongussuki"
author = "XDakanX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc9f13e988e89cf0741a24925ed90ac8fcacde3c236a36fd18a1da61e649133e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
