name = "amongussuki"
author = "XDakanX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f2fe3bf66af9386a03d87fd05df2ae1b9d764cfce5054f0442a4204a90ebd7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
