name = "amongussuki"
author = "XDakanX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "859e2b4e9d4b01747e0a2226921ed786790381a1909b096f38afc3dfeec4125b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
